const Countries = [
  {
    ru: "Корея, Республика Южная Корея",
    lt: "korėja, Pietų korėjos Respublika",
    tr: "Güney kore Cumhuriyeti",
    en: "South Korea",
    ko: "대한민국",
    flag: "🇰🇷",
    code: "KO",
    dialCode: "+82",
    mask: "999-9999-9999",
  },
  {
    ru: "Китай",
    lt: "Kinija",
    tr: "Çin",
    en: "China",
    ko: "중국",
    flag: "🇨🇳",
    code: "CN",
    dialCode: "+86",
    mask: "999 9999 9999",
  },
  {
    ru: "Япония",
    lt: "Japonija",
    tr: "Japonya",
    en: "Japan",
    ko: "일본",
    flag: "🇯🇵",
    code: "JP",
    dialCode: "+81",
    mask: "999-9999-9999",
  },
  {
    ru: "Соединенные Штаты",
    lt: "Jungtinės Valstijos",
    tr: "Amerika Birleşik Devletleri",
    en: "United States",
    ko: "미국",
    flag: "🇺🇸",
    code: "US",
    dialCode: "+1",
    mask: "(999) 999-9999",
  },
  {
    ru: "Австралия",
    lt: "Australija",
    tr: "Avustralya",
    en: "Australia",
    ko: "호주",
    flag: "🇦🇺",
    code: "AU",
    dialCode: "+61",
    mask: "9999 999 999",
  },
  {
    ru: "объединенное Королевство",
    lt: "Jungtinė Karalystė",
    tr: "Birleşik koallık",
    en: "United Kingdom",
    ko: "영국",
    flag: "🇬🇧",
    code: "GB",
    dialCode: "+44",
    mask: "99999 999999",
  },
  {
    ru: "Новая Зеландия",
    lt: "Naujoji Zelandija",
    tr: "Yeni Zelanda",
    en: "New Zealand",
    ko: "뉴질랜드",
    flag: "🇳🇿",
    code: "NZ",
    dialCode: "+64",
    mask: "999 999 9999",
  },
  {
    ru: "Бразилия",
    lt: "Brazilija",
    tr: "Brezilya",
    en: "Brazil",
    ko: "브라질",
    flag: "🇧🇷",
    code: "BR",
    dialCode: "+55",
    mask: "(99) 99999 9999",
  },
];

export default Countries;
